### ISSUE TITLE
Failure to install necessary packages

### ISSUE THREAD

**Issue by MicTott** [DeniseCaiLab/ezTrack#1]
When attempting to install the necessary packages,

1. `conda config --add channels conda-forge`
2. `conda create -n ezTrack python=3.6.5 pandas=0.23.0 matplotlib=2.2.2 opencv=3.4.3 jupyter holoviews scipy`

I get the following error message after running step 2 

`The following NEW packages will be INSTALLED:`

    appnope:            0.1.0-py36_1000                      conda-forge
    attrs:              19.1.0-py_0                          conda-forge
    backcall:           0.1.0-py_0                           conda-forge
    blas:               1.1-openblas                         conda-forge
    bleach:             3.1.0-py_0                           conda-forge
    bokeh:              1.1.0-py36_0                         conda-forge
    bzip2:              1.0.6-h1de35cc_1002                  conda-forge
    ca-certificates:    2019.3.9-hecc5488_0                  conda-forge
    cairo:              1.14.12-h9d4d9ac_1005                conda-forge
    certifi:            2019.3.9-py36_0                      conda-forge
    cycler:             0.10.0-py_1                          conda-forge
    decorator:          4.4.0-py_0                           conda-forge
    defusedxml:         0.5.0-py_1                           conda-forge
    entrypoints:        0.3-py36_1000                        conda-forge
    ffmpeg:             4.0.2-ha0c5888_2                     conda-forge
    fontconfig:         2.13.1-h1027ab8_1000                 conda-forge
    freetype:           2.10.0-h24853df_0                    conda-forge
    gettext:            0.19.8.1-h46ab8bc_1002               conda-forge
    giflib:             5.1.7-h01d97ff_1                     conda-forge
    glib:               2.56.2-h67dad55_1001                 conda-forge
    gmp:                6.1.2-h0a44026_1000                  conda-forge
    gnutls:             3.5.19-h2a4e5f8_1                    conda-forge
    graphite2:          1.3.13-h2098e52_1000                 conda-forge
    harfbuzz:           1.9.0-h9889186_1001                  conda-forge
    hdf5:               1.10.3-hfa1e0ec_1001                 conda-forge
    holoviews:          1.12.1-py_2                          conda-forge
    icu:                58.2-h0a44026_1000                   conda-forge
    ipykernel:          5.1.0-py36h24bf2e0_1002              conda-forge
    ipython:            7.5.0-py36h24bf2e0_0                 conda-forge
    ipython_genutils:   0.2.0-py_1                           conda-forge
    ipywidgets:         7.4.2-py_0                           conda-forge
    jasper:             1.900.1-h636a363_1006                conda-forge
    jedi:               0.13.3-py36_0                        conda-forge
    jinja2:             2.10.1-py_0                          conda-forge
    jpeg:               9c-h1de35cc_1001                     conda-forge
    jsonschema:         3.0.1-py36_0                         conda-forge
    jupyter:            1.0.0-py_2                           conda-forge
    jupyter_client:     5.2.4-py_3                           conda-forge
    jupyter_console:    6.0.0-py_0                           conda-forge
    jupyter_core:       4.4.0-py_0                           conda-forge
    kiwisolver:         1.1.0-py36h770b8ee_0                 conda-forge
    libblas:            3.8.0-5_hd44dcd8_netlib              conda-forge
    libcblas:           3.8.0-5_hd44dcd8_netlib              conda-forge
    libcxx:             8.0.0-2                              conda-forge
    libcxxabi:          8.0.0-2                              conda-forge
    libffi:             3.2.1-h6de7cb9_1006                  conda-forge
    libgfortran:        3.0.1-0                              conda-forge
    libiconv:           1.15-h01d97ff_1005                   conda-forge
    liblapack:          3.8.0-5_hd44dcd8_netlib              conda-forge
    libpng:             1.6.37-h2573ce8_0                    conda-forge
    libsodium:          1.0.16-h1de35cc_1001                 conda-forge
    libtiff:            4.0.10-h79f4b77_1001                 conda-forge
    libwebp:            0.5.2-7                              conda-forge
    libxml2:            2.9.9-hd80cff7_0                     conda-forge
    markupsafe:         1.1.1-py36h1de35cc_0                 conda-forge
    matplotlib:         2.2.2-py36hbf02d85_2                            
    mistune:            0.8.4-py36h1de35cc_1000              conda-forge
    nbconvert:          5.5.0-py_0                           conda-forge
    nbformat:           4.4.0-py_1                           conda-forge
    ncurses:            6.1-h0a44026_1002                    conda-forge
    nettle:             3.3-0                                conda-forge
    notebook:           5.7.8-py36_0                         conda-forge
    numpy:              1.15.2-py36_blas_openblashd3ea46f_1  conda-forge [blas_openblas]
    olefile:            0.46-py_0                            conda-forge
    openblas:           0.2.20-8                             conda-forge
    opencv:             3.4.3-py36_blas_openblash5e3fa27_201 conda-forge [blas_openblas]
    openh264:           1.8.0-hd9629dc_1000                  conda-forge
    openssl:            1.0.2r-h1de35cc_0                    conda-forge
    packaging:          19.0-py_0                            conda-forge
    pandas:             0.23.0-py36_1                        conda-forge
    pandoc:             2.7.2-0                              conda-forge
    pandocfilters:      1.4.2-py_1                           conda-forge
    param:              1.9.0-py_0                           conda-forge
    parso:              0.4.0-py_0                           conda-forge
    pcre:               8.41-h0a44026_1003                   conda-forge
    pexpect:            4.7.0-py36_0                         conda-forge
    pickleshare:        0.7.5-py36_1000                      conda-forge
    pillow:             6.0.0-py36h7095ceb_0                 conda-forge
    pip:                19.1-py36_0                          conda-forge
    pixman:             0.34.0-h1de35cc_1003                 conda-forge
    prometheus_client:  0.6.0-py_0                           conda-forge
    prompt_toolkit:     2.0.9-py_0                           conda-forge
    ptyprocess:         0.6.0-py_1001                        conda-forge
    pygments:           2.3.1-py_0                           conda-forge
    pyparsing:          2.4.0-py_0                           conda-forge
    pyqt:               5.6.0-py36hc26a216_1008              conda-forge
    pyrsistent:         0.15.1-py36h01d97ff_0                conda-forge
    python:             3.6.5-1                              conda-forge
    python-dateutil:    2.8.0-py_0                           conda-forge
    pytz:               2019.1-py_0                          conda-forge
    pyviz_comms:        0.7.2-py_0                           conda-forge
    pyyaml:             5.1-py36h1de35cc_0                   conda-forge
    pyzmq:              18.0.1-py36h2d07e9b_1                conda-forge
    qt:                 5.6.2-h9e3eb04_4                     conda-forge
    qtconsole:          4.4.3-py_0                           conda-forge
    readline:           7.0-hcfe32e1_1001                    conda-forge
    scipy:              1.2.1-py36hbd7caa9_1                 conda-forge
    send2trash:         1.5.0-py_0                           conda-forge
    setuptools:         41.0.1-py36_0                        conda-forge
    sip:                4.18.1-py36h0a44026_1000             conda-forge
    six:                1.12.0-py36_1000                     conda-forge
    sqlite:             3.20.1-0                             conda-forge
    terminado:          0.8.2-py36_0                         conda-forge
    testpath:           0.4.2-py_1001                        conda-forge
    tk:                 8.6.9-ha441bb4_1001                  conda-forge
    tornado:            6.0.2-py36h01d97ff_0                 conda-forge
    traitlets:          4.3.2-py36_1000                      conda-forge
    wcwidth:            0.1.7-py_1                           conda-forge
    webencodings:       0.5.1-py_1                           conda-forge
    wheel:              0.33.1-py36_0                        conda-forge
    widgetsnbextension: 3.4.2-py36_1000                      conda-forge
    x264:               1!152.20180806-h1de35cc_0            conda-forge
    xz:                 5.2.4-h1de35cc_1001                  conda-forge
    yaml:               0.1.7-h1de35cc_1001                  conda-forge
    zeromq:             4.3.1-h0a44026_1000                  conda-forge
    zlib:               1.2.11-h1de35cc_1004                 conda-forge

```
Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(507): An error occurred while installing package 'conda-forge::attrs-19.1.0-py_0'.
FileNotFoundError(2, "No such file or directory: '/Users/home/anaconda3/envs/ezTrack/bin/python3.6'")
Attempting to roll back.


Rolling back transaction: done
```

When I check for the missing directory i find '/Users/home/anaconda3/envs/ezTrack/conda-meta', but not '/bin/python3.6'. Any idea what the issue might be? I'm looking forward to testing out this software!

**Comment by DeniseCaiLab** [comment]
Hi,
This might have to do with matplotlib being installed from the default Anaconda3 channel instead of conda-forge (because I didn't realize it wasn't available through conda-forge), which may be creating a compatibility issue during install.  I would try the following:
1 - Delete the '/Users/home/anaconda3/envs/ezTrack' folder
2 - In terminal, enter the following command: `conda create -n ezTrack -c conda-forge python=3.6 pandas=0.23.0 matplotlib  opencv=3.4.3 jupyter holoviews scipy`
Let me know if this solves the problem and I'll update the install instructions on github.

**Comment by MicTott** [comment]
After upgrading conda from 4.5.12 to 4.6.14 and following your new instructions this worked like a charm! Not sure if my outdated conda was actually the issue in the first place, but thanks for the quick reply!
