### ISSUE TITLE
LocationTracking_Individual: problem when changing tracking parameters

### ISSUE THREAD

**Issue by LJB1** [DeniseCaiLab/ezTrack#10]
Hi,

This tool is proving to be invaluable for me, so thanks!

I have been having success with this code so far but have just encountered a problem. For some of my videos I would like to change the 'method' in 'tracking_params' (section 7a. Set Location Tracking Parameters) from 'abs' to 'dark'. I notice that for some videos the display examples in 7b are more accurate when I use 'dark' instead of 'abs', hence I would like to change from the default tracking parameters.

In case it is relevant, I split the video being analysed into three areas ('Left', 'Centre', 'Right') and am interested in determining the relative time spent in each. However, when I run the code, the summary stats for the 'Centre' and 'Right' columns have the value '0', with only the 'Left' column having a value (e.g. 0.4132). 

I was wondering if you could shed any light on this problem?

Thanks in advance,

Luke

**Comment by ZachPenn** [comment]
Hi Luke,

Glad to hear ezTrack is helpful to you.  You should be able to switch from method 'abs' to method 'dark' for both individual and batch location processing without any issues.  The only reason 'abs' is the default is that it works regardless of whether the animal is lighter/darker than the background, and also seems to work a bit better if an animal is moving between regions of high/low contrast.

The Left/Center/Right issue you seem to be having is a bit elusive to me and it would be helpful to know some more details. Does this only happen when using method 'dark'?  When viewing the trace of the animal across the session, is it clear that the animal entered regions 'Centre' and 'Right'? If you could provide screenshots of your drawn regions of interest, the animal trace across the session, and and the binned summary report output, perhaps we can solve this issue.

Best,
Zach
