### ISSUE TITLE
Program Crash

### ISSUE THREAD

**Issue by TM665** [DeniseCaiLab/ezTrack#11]
Hi,
When I am using the location tracking function (individual) when I get to 7c the page crashes and I am not sure why.

**Comment by TM665** [comment]
> Hi,
> When I am using the location tracking function (individual) when I get to 7c the page crashes and I am not sure why.

I actually have this message in the command window:
[IPKernelApp] WARNING | No such comm: hv-extension-comm

**Comment by ZachPenn** [comment]
I would need more info but it sounds like it has something to do with the conda environment /package versions installed.  After activating the conda env, if you enter `conda list` in the terminal I may be able to help diagnose the issue.

**Comment by TM665** [comment]
Absolutely. I’m not sure where to even begin as I’m new to this but whatever information you need if I can I will provide.


Tyler

On Jan 1, 2020, at 16:47, Zach Pennington <notifications@github.com> wrote:

﻿

I would need more info but it sounds like it has something to do with the conda environment /package versions installed. After activating the conda env, if you enter conda list in the terminal I may be able to help diagnose the issue.

**Comment by ZachPenn** [comment]
After activating the conda env, if you enter conda list in the terminal it will provide you with a list of packages and package versions.  If you could provide this list to me that would be helpful.

Also, have you tried restarting and clearing the output from the kernel and re-running everything (Within Jupyter Notebook, Kernel -> Restart and Clear Output)?  Is the error reproducible?
