### ISSUE TITLE
only the first Holoviews object is displaying in LocationTracking_Individual

### ISSUE THREAD

**Issue by smawe** [DeniseCaiLab/ezTrack#13]
When running through LocationTracking_Individual the first holoview object from step 3 "Load Video and Crop Frame" displays properly, but no image is displayed for step 4 "Defining Reference Frame for Location Tracking" and neither does the interactive object for setting the scale in step 6a "Define Scale for Distance Calculations"

**Comment by ZachPenn** [comment]
Did you crop the image?  Have you tried adjusting the output size at the top of the cell?
