### ISSUE TITLE
Glitch for using reference frames (Option 2)

### ISSUE THREAD

**Issue by scimemia** [DeniseCaiLab/ezTrack#17]
The Reference function, which generates the reference frame, uses the same video_dict defined for the video to be analyzed. The 'start' and 'end' variables for the 'altfile' are the same as the 'start' and 'end' values for the file to be analyzed. This means that if the value of 'start' is higher than the number of frames in the reference video (as it is in our case), the code does not manage to  find frames in the reference video and generates an error message. Is there any chance to create separate 'start' and 'end' variables for the video to be analyzed and the reference video? Do you think it would be appropriate to add to the Jupyter Notebook a couple of lines to create the reference video using a subset of frames in the video to be analyzed, without having to use a different software? If not, we can modify the code. I was not sure whether this could be useful to the broader community. Thanks!

**Comment by ZachPenn** [comment]
Thank you so much for pointing this out.  This is definitely something we want resolved for anyone using ezTrack.  The function to generate the reference frame now allows the user to pass a list defining the frame numbers they would like to use for generating the reference.  Please re-download the LocationTracking_Functions.py and LocationTracking_Individual.ipynb files to see the changes (or use 'git pull' if you are a git user).
