### ISSUE TITLE
Package Loading issue in Jupyter Notebook

### ISSUE THREAD

**Issue by natalier11** [DeniseCaiLab/ezTrack#19]
Hi there!

I've gotten the EZtrack Jupyter Notebook to work in the past and even analyzed videos but I'm running into a bit of an error now. After setting up the environment, downloading the zip, and opening jupyter notebook, I try to run the first step on the "LocationTracking_Individual.ipynb" file. When I run the cell containing all the necessary packages, it returns a message saying "WARNING:param.Dimension: Use method 'get_param_values' via param namespace" about 50 times, followed by "WARNING:param.ParameterizedMetaclass: Use method 'params' via param namespace" another 50 times, and then "WARNING:param.BokehRenderer: Use method 'params' via param namespace 
WARNING:param.NotebookArchive: Use method 'params' via param namespace"
I've never run into this before and I thought I might ignore it and continue with my video analysis but it seems to affect step 3. When I try to run the Load Video and Crop Frame step, this pops up:
![Step 3 Error Message](https://user-images.githubusercontent.com/73397911/97817069-9c055c80-1c5f-11eb-8268-06233bf34332.png)
![Step 3 Error Message Pt2](https://user-images.githubusercontent.com/73397911/97817075-9e67b680-1c5f-11eb-95f1-6fa3c3d78d44.png)
I'm not sure if the video is potentially too long or there is some other issue going on. Help would be much appreciated! Thank you!

**Comment by ZachPenn** [comment]
Hi,

Sorry to hear you're having issues.  I have a feeling this might have to do with package versions, as opposed to an issue with your video.  Did you follow the install instructions, including package versions in the install?  In any event, from terminal, could you activate the conda environment, enter the command `conda list` and then copy the output of that command here?

**Comment by natalier11** [comment]
Thanks for responding!
I followed the install instructions provided by the github (I thought I did it wrong the first time so actually uninstalled everything and did it again with the github instructions). Here is the list of packages I have installed at the moment that I obtained from the terminal:
# Name                    Version                   Build  Channel
argon2-cffi               20.1.0           py36h779f372_2    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     20.2.0             pyh9f0ad1d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
blas                      1.0                         mkl
bleach                    3.2.1              pyh9f0ad1d_0    conda-forge
bokeh                     1.2.0                    py36_0    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py36hd36e781_2    conda-forge
cffi                      1.14.3           py36h2e103f8_1    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
entrypoints               0.3             py36h9f0ad1d_1002    conda-forge
freetype                  2.10.4               h546665d_0    conda-forge
holoviews                 1.12.3                     py_2    conda-forge
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha925a31_3
importlib-metadata        2.0.0                      py_1    conda-forge
importlib_metadata        2.0.0                         1    conda-forge
intel-openmp              2020.2                      254
ipykernel                 5.3.4            py36h7b7c402_1    conda-forge
ipython                   7.16.1           py36h95af2a2_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1              pyh9f0ad1d_1    conda-forge
jedi                      0.17.2           py36h9f0ad1d_1    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
jsonschema                3.2.0                      py_2    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            6.1.7                      py_0    conda-forge
jupyter_console           6.2.0                      py_0    conda-forge
jupyter_core              4.6.3            py36h9f0ad1d_2    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
kiwisolver                1.3.0            py36he95197e_0    conda-forge
libblas                   3.8.0                    20_mkl    conda-forge
libcblas                  3.8.0                    20_mkl    conda-forge
liblapack                 3.8.0                    20_mkl    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libsodium                 1.0.18               h62dcd97_1    conda-forge
libtiff                   4.1.0                h885aae3_6    conda-forge
libwebp                   0.5.2                         7    conda-forge
lz4-c                     1.9.2                h62dcd97_2    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                1.1.1            py36hc753bc4_2    conda-forge
matplotlib                3.1.1                    py36_2    conda-forge
matplotlib-base           3.1.1            py36h2981e6d_2    conda-forge
mistune                   0.8.4           py36h779f372_1002    conda-forge
mkl                       2020.2                      256
msys2-conda-epoch         20160418                      1
nbclient                  0.5.1                      py_0    conda-forge
nbconvert                 6.0.7            py36h9f0ad1d_2    conda-forge
nbformat                  5.0.8                      py_0    conda-forge
nest-asyncio              1.4.1                      py_0    conda-forge
notebook                  6.1.4            py36h9f0ad1d_1    conda-forge
numpy                     1.19.2           py36hc5bf2d3_1    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
opencv                    3.4.3           py36h597e314_201    conda-forge
openssl                   1.0.2u               hfa6e2cd_0    conda-forge
packaging                 20.4               pyh9f0ad1d_0    conda-forge
pandas                    0.23.0                   py36_1    conda-forge
pandoc                    2.11.0.4             hf4a77e7_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
param                     1.10.0                     py_0    conda-forge
parso                     0.7.1              pyh9f0ad1d_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.0.1            py36he4e95fe_0    conda-forge
pip                       20.2.4                     py_0    conda-forge
prometheus_client         0.8.0              pyh9f0ad1d_0    conda-forge
prompt-toolkit            3.0.8                      py_0    conda-forge
prompt_toolkit            3.0.8                         0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.7.2                      py_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.6.0           py36h764d66f_1008    conda-forge
pyrsistent                0.17.3           py36h779f372_1    conda-forge
python                    3.6.11          h6f26aa1_2_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.6                     1_cp36m    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pyviz_comms               0.7.6              pyh9f0ad1d_0    conda-forge
pywin32                   228              py36h779f372_0    conda-forge
pywinpty                  0.5.7            py36h9f0ad1d_1    conda-forge
pyyaml                    5.3.1            py36hc753bc4_1    conda-forge
pyzmq                     19.0.2           py36h274d426_2    conda-forge
qt                        5.6.2           vc14h6f8c307_12
qtconsole                 4.7.7              pyh9f0ad1d_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
scipy                     1.2.1            py36h29ff71c_0
send2trash                1.5.0                      py_0    conda-forge
setuptools                49.6.0           py36hd36e781_2    conda-forge
sip                       4.18.1          py36h6538335_1000    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.33.0               he774522_1    conda-forge
terminado                 0.9.1            py36h9f0ad1d_1    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tk                        8.6.10               he774522_1    conda-forge
tornado                   6.1              py36h68aa20f_0    conda-forge
traitlets                 4.3.3            py36h9f0ad1d_1    conda-forge
vc                        14.1                 h869be7e_1    conda-forge
vs2015_runtime            14.16.27012          h30e32a0_2    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
widgetsnbextension        3.5.1            py36h9f0ad1d_4    conda-forge
wincertstore              0.2             py36h9f0ad1d_1005    conda-forge
winpty                    0.4.3                         4    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
zeromq                    4.3.2                ha925a31_4    conda-forge
zipp                      3.4.0                      py_0    conda-forge
zlib                      1.2.11            h62dcd97_1010    conda-forge
zstd                      1.4.5                h1f3a1b7_2    conda-forge

**Comment by ZachPenn** [comment]
Can I also ask what operating system and browser you are using?

**Comment by natalier11** [comment]
I am using Windows 10 and Mozilla for my browser.

**Comment by ZachPenn** [comment]
I will be looking further into this over the next few days when I can get some time.  It is a problem that is specific to Windows and has to do with package dependencies, rather than ezTrack code.  This may take me a few days.  

Zach

**Comment by natalier11** [comment]
No problem! Thanks for your assistance!

**Comment by ZachPenn** [comment]
I think the issue can be resolved by updating a couple of packages.  For some reason I had better luck uninstalling the ezTrack environment and then reinstalling than simply updating the specific packages.

If you are unfamiliar with removing environments, you can use the following command:
`conda remove --name ezTrack --all`

Subsequently, reinstall the ezTrack conda environment with the following command:
`conda create -y -n ezTrack -c conda-forge python=3.6 pandas=0.23.0 matplotlib=3.1.1 opencv=3.4.3 jupyter=1.0.0 holoviews=1.13.5 scipy=1.2.1 bokeh=2.1.1`

So far this has been tested on Windows using Chrome and Mozilla Firefox browsers and on Mac using Chrome.

Please let me know if this works for you and thanks for bringing this to my attention.

**Comment by natalier11** [comment]
Hi there! I was able to uninstall the environments adreinstall them with your command line no problem. However, now when I try to run the first cell in the notebook, I get an error message that says:
Javascript error adding output!
TypeError: t.slice is not a function
See your browser Javascript console for more details.

I've never received this type of error message on anything and I'm not sure how to fix this. Let me know if you have any ideas.

**Comment by natalier11** [comment]
The cell seems to run even with that error but once I get to step 3, it shows the following output:
![Step 3 output](https://user-images.githubusercontent.com/73397911/98310053-ad1cd900-1f91-11eb-8729-dd3f03c7ccc1.png)
It also shows this message in the anaconda prompt when I run step 3:
[IPKernelApp] WARNING | No such comm: hv-extension-comm

I am not sure if this has to do with the environments again.

**Comment by ZachPenn** [comment]
Definitely has something to do with the environment.  This is the same issue I had when I at first tried to update the packages without uninstalling the environment first, but I suppose that's not the solution.  Will look into this more.

**Comment by ZachPenn** [comment]
I have now tested ezTrack with the updated conda environment install instructions that I provided you on two computers running Windows and with four browsers (Chrome, Edge, Firefox, and Explorer).  I only get the error you describe when using Internet Explorer.  ezTrack works on all other browsers.  Were you using Internet Explorer?

**Comment by natalier11** [comment]
That's really odd because I've only ever used Firefox through this whole process. Let me try Chrome and see if that may help.

**Comment by natalier11** [comment]
It appears that using Chrome works with no issues!! Thanks so much for all your help, I really appreciate it!
