### ISSUE TITLE
The issues in the LocationTracking_Functions.py?

### ISSUE THREAD

**Issue by wangjiuwei** [DeniseCaiLab/ezTrack#20]
when i run the 1. Load Necessary Packages of LocationTracking_Individual.ipynb, there are something wrong,

WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.Dimension: Use method 'get_param_values' via param namespace 
WARNING:param.ParameterizedMetaclass: Use method 'params' via param namespace

**Comment by wangjiuwei** [comment]
sorry, i will check previous issue and try to solve the problems by myself.^_^

**Comment by ZachPenn** [comment]
Please see https://github.com/DeniseCaiLab/ezTrack/issues/19.  This was recently solved.

**Comment by wangjiuwei** [comment]
Thank you very much！

**Comment by wangjiuwei** [comment]
Thank you very much！It works!!!
