### ISSUE TITLE
Problem in defining the ROI

### ISSUE THREAD

**Issue by SPHN-Joe** [DeniseCaiLab/ezTrack#21]
Hello,
I am trying to define the ROI in step number 6. When I try to double-click on the image, the blue dot doesn't show on the image as shown in the attached picture. Do you have any suggestion about this problem? Thanks in advance for any help that you are able to provide.
![Picture1](https://user-images.githubusercontent.com/61629499/111058123-d52bc400-84be-11eb-82de-3f5a7e6941fd.png)

**Comment by ZachPenn** [comment]
Yes, you need to define your regions of interest in line 10 of Cell 2:
![image](https://user-images.githubusercontent.com/38541976/112017985-82788a80-8b04-11eb-865a-21f32101ff17.png)
