### ISSUE TITLE
ezTrack LocationTracking_Individual Step 5

### ISSUE THREAD

**Issue by TimOnofrychuk** [DeniseCaiLab/ezTrack#22]
Hello, 

Across multiple OS's, step 5 of the location tracking module seems to be impassible. I'm not sure if this is simply a problem with the version of modules I have installed, and if so, is there a location that module versions used for the original implementation can be found?

Thanks in advance for your advice.

**Comment by TimOnofrychuk** [comment]
Thank you for your response. 

No errors appear as I run Option 1 of Step 5 (screenshot attached), "impassible" was referring to how the function doesn't seem to be returning a reference image after ample time. I have also attached a screenshot of the current venv I am trying to run this on. 

If there is no obvious solution, I have had awesome luck with the earlier version and have no problem going back. Thanks!
![Screen Shot 2021-03-20 at 11 41 33 PM](https://user-images.githubusercontent.com/64874200/111895136-29123d80-89d6-11eb-894a-698a0b0f7165.png)
![Screen Shot 2021-03-20 at 11 28 50 PM](https://user-images.githubusercontent.com/64874200/111895140-33ccd280-89d6-11eb-9ddc-0efc5382390c.png)

**Comment by ZachPenn** [comment]
Long story short, there was an issue with how ezTrack handles corrupt frames that I just pushed a fix for.  I have a feeling you will encounter the same issue with the old version of ezTrack with the video you are currently processing and recommend trying this.  I would download ezTrack again, or just download the file `LocationTracking_functions.py` and replace it in your ezTrack folder.

**Comment by TimOnofrychuk** [comment]
Worked like a charm, thank you for taking care of that. It seems that another downstream problem might have popped up. I have attached a screenshot, and will note that 8a ran substantially faster than what I have experienced in the past prior to the error. 
![Screen Shot 2021-03-23 at 10 39 07 AM](https://user-images.githubusercontent.com/64874200/112184183-92f03a00-8bc4-11eb-8866-785cf41d9873.png)

**Comment by ZachPenn** [comment]
This was a very similar issue to before and has also now been fixed.  You can re-download the LocationTracking_Functions.py file and it should work.  I am somewhat concerned that you have a fairly large number of corrupt/unreadable frames in your video files.  It's not uncommon to have a few unreadable frames every once in a while (elsewhere ezTrack already handles these bad frames), but stumbling upon both of these bugs may indicate an issue.  When ezTrack first prints file info in Cell 3, it includes the total number of frames, irrespective of whether there are any corrupt/unreadable frames.  If the number of frames processed in 8c is substantially less than this (<99%) I would look into your recording setup.

**Comment by TimOnofrychuk** [comment]
Everything is working great now, thank you for your advice and help with this! (this was an old example video, so I have switched to using a higher quality vid)
