### ISSUE TITLE
installing in Ubuntu 20.04

### ISSUE THREAD

**Issue by ckemere** [DeniseCaiLab/ezTrack#23]
I'm having issues with holoviews/bokeh under Ubuntu 20.04. In particular, I'm not able to get any dynamic output in my notebooks. Anyone solve this successfully?

**Comment by ZachPenn** [comment]
What web browser are you using?  We've experienced intermittent complications with everything except Chrome.  Also, have you tried to increase the output size in the first line of each cell?  Sometimes with smaller videos holoviews images won't appear without increasing output size.  If neither of these work, it may be necessary to update holoviews/bokeh package versions.

**Comment by ckemere** [comment]
My default is Firefox, but based on your comment, I tried again with Chrome. It is the case that the videos I'm looking at are `dimensions (h x w): 80,630`, but if I zoom in I still just see an empty box. I haven't specified the versions of holoviews and bokeh as described in the instructions (just python/opencv). I will try again with that and see if that changes things.

**Comment by ckemere** [comment]
Update - I tried with the precise package versions suggested and, then changed the notebook magic, `%%output size=100`
from 100 to 400, and now it's working! Thanks!
