### ISSUE TITLE
TypeError during Display examples of Location tracking to confirm threshold (8b)

### ISSUE THREAD

**Issue by HLRosaC** [DeniseCaiLab/ezTrack#24]
![Error_message_01](https://user-images.githubusercontent.com/82155760/114024625-3f156e80-98af-11eb-825c-ed88e4e50f5e.png)

Hi!
I am struggling to analysis the tracking behavior and this is very useful for me who is very new in python or computation.
I tried to search the previous mentioned issues, but I couldn't find answer to figure out my error above.

Which step do I have to check or... what should I do to solve the problem??

**Comment by ZachPenn** [comment]
Hello, 

I apologize for this issue and the delay.  I was in the midst of a series of ezTrack updates and this error was introduced in the process.  If you re-download the eztrack files from github now, all should work.  Let me know if you have any issues.

Zach
