### ISSUE TITLE
Lag in location tracker in individual analysis video generated in step 10.

### ISSUE THREAD

**Issue by ewo478** [denisecailab/ezTrack#26]
Hello
I've noticed there's a lag in the marker on the video generated in the individual tracker analysis step 10. The attached screenshot is an example of this where the animal has moved into a new region of interest but the marker in the video lag behind. Would the frames that have the animal in the next region but the lagging marker be counted as TRUE for the first region, or is the analysis more accurate? 

This also could interfere with analyses of zones the animal circumnavigates but doesn't enter as the marker crosses the unentered zone as it catches up to the animal, second pic. 
![Screenshot 2021-04-15 154200](https://user-images.githubusercontent.com/82358639/114810919-294cff80-9e01-11eb-8e0f-fb2d4a78cbbb.png)

**Comment by ZachPenn** [comment]
If these are the same videos you previously reached out about that have a larger number of missing frames than the display feature won't work correct.
