### ISSUE TITLE
Typeerror when loading packages

### ISSUE THREAD

**Issue by GrantM-ed** [denisecailab/ezTrack#30]
Keep getting errors when loading the initial packages...

![image](https://user-images.githubusercontent.com/86917379/124386159-fcf2a200-dcd0-11eb-9e76-8c4315212d7c.png)

Getting this problem in V1.1 and in the version uploaded in May 2021. I've reinstalled everything from scratch and my eztrack conda environment is definitely active and includes holoviews and bokeh...

**Comment by ZachPenn** [comment]
Is this the full error report?  If not, it would be helpful to see the full thing.  What web browser is this in?

**Comment by GrantM-ed** [comment]
> Is this the full error report? If not, it would be helpful to see the full thing. What web browser is this in?

Hi, sorry this is the full report:

------------------------
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-dbcd4a23ec0c> in <module>
      2 get_ipython().run_line_magic('autoreload', '2')
      3 import os
----> 4 import holoviews as hv
      5 import numpy as np
      6 import pandas as pd

~\miniconda3\envs\ezTrack\lib\site-packages\holoviews\__init__.py in <module>
     10 
     11 from . import util                                       # noqa (API import)
---> 12 from .annotators import annotate                         # noqa (API import)
     13 from .core import archive, config                        # noqa (API import)
     14 from .core.boundingregion import BoundingBox             # noqa (API import)

~\miniconda3\envs\ezTrack\lib\site-packages\holoviews\annotators.py in <module>
      8 import param
      9 
---> 10 from panel.pane import PaneBase
     11 from panel.layout import Row, Tabs
     12 from panel.util import param_name

~\miniconda3\envs\ezTrack\lib\site-packages\panel\__init__.py in <module>
      3 import param as _param
      4 
----> 5 from . import layout # noqa
      6 from . import links # noqa
      7 from . import pane # noqa

~\miniconda3\envs\ezTrack\lib\site-packages\panel\layout.py in <module>
     22 from .io.state import state
     23 from .util import param_name, param_reprs
---> 24 from .viewable import Layoutable, Reactive
     25 
     26 _row = namedtuple("row", ["children"])

~\miniconda3\envs\ezTrack\lib\site-packages\panel\viewable.py in <module>
     40 
     41 
---> 42 class Layoutable(param.Parameterized):
     43 
     44     align = param.ObjectSelector(default='start',

~\miniconda3\envs\ezTrack\lib\site-packages\panel\viewable.py in Layoutable()
     60 
     61     css_classes = param.List(default=None, doc="""
---> 62         CSS classes to apply to the layout.""")
     63 
     64     width = param.Integer(default=None, bounds=(0, None), doc="""

~\miniconda3\envs\ezTrack\lib\site-packages\param\__init__.py in __init__(self, default, class_, item_type, instantiate, bounds, **params)
   1388         Parameter.__init__(self, default=default, instantiate=instantiate,
   1389                            **params)
-> 1390         self._validate(default)
   1391 
   1392     def _validate(self, val):

~\miniconda3\envs\ezTrack\lib\site-packages\param\__init__.py in _validate(self, val)
   1396         """
   1397         self._validate_value(val, self.allow_None)
-> 1398         self._validate_bounds(val, self.bounds)
   1399         self._validate_item_type(val, self.item_type)
   1400 

~\miniconda3\envs\ezTrack\lib\site-packages\param\__init__.py in _validate_bounds(self, val, bounds)
   1404             return
   1405         min_length, max_length = bounds
-> 1406         l = len(val)
   1407         if min_length is not None and max_length is not None:
   1408             if not (min_length <= l <= max_length):

TypeError: object of type 'NoneType' has no len()

---------------------

This is in chrome Version 91.0.4472.124 (Official Build) (64-bit)

**Comment by ZachPenn** [comment]
Did you follow the install instructions exactly?  Some people have installed ezTrack packages using different package versions and had issues.

**Comment by GrantM-ed** [comment]
Hi  -yes I followed the instructions exactly for the installation of the packages. I ended up moving to another PC which worked fine so I'm closing this, thanks!
