### ISSUE TITLE
issue with exporting .png pictures

### ISSUE THREAD

**Issue by h1408** [denisecailab/ezTrack#32]
Hello, I am trying to use the save feature to download the .png images from all steps in the code, however it is being cropped when it's saved to my Downloads. I've attached some examples. Is there anything I can do to fix this? Thank you! 
![7 1Step8b(2)](https://user-images.githubusercontent.com/80368001/125670656-65542b60-0e56-494c-9ed7-348e91f5a594.png)
![7 1Step3](https://user-images.githubusercontent.com/80368001/125670661-e98672ce-be05-4aea-8587-710f865b16fb.png)
![7 1Step8d(1)](https://user-images.githubusercontent.com/80368001/125670670-7a826a35-20f3-4fa3-85b0-71fca5ca94a4.png)

**Comment by ZachPenn** [comment]
This is an issue with the specific versions of Holoviews/Bokeh being used.  I am currently testing newer versions, which appears to address this issue.  Once this is complete across all operating systems I will update environment install instructions.

**Comment by ZachPenn** [comment]
This environment is working for me on OSX with Google Chrome:

```
conda create -y -n ezTrack -c conda-forge python=3.8 pandas=1.3.2 matplotlib=3.1.1 opencv=4.5.3 jupyter=1.0.0 holoviews=1.14.5 scipy=1.7.1 scikit-learn=0.24.2 bokeh=2.3.3 tqdm
```

I haven't gotten a chance to test it on anything else, so if you try this on any other operating system/browser and it resolves your problem please let me know.

Note that if you already have an environment named `ezTrack` you'll either want to name the new environment something else or remove it first, which you can do in terminal with the following command:

```
conda remove --name ezTrack --all
```

**Comment by h1408** [comment]
Hi Zach, YEs this has worked on another operating system and browser (Windows on Microsoft edge). Thank you so much!

**Comment by h1408** [comment]
Hello,
While this had worked on a Windows computer, I went back and removed my old ezTrack env on my Macbook and reinstalled the environment using the same specifications as you mention above. However, I ran into an error when trying to run the first step:
`ImportError: cannot import name 'Markup' from 'jinja2' (/Users/haniyyah/miniconda3/envs/ezTrack/lib/python3.8/site-packages/jinja2/__init__.py)` showed up when I tried to run step 1. When I hit run again I get another different error:
`ImportError: cannot import name 'config' from partially initialized module 'panel.config' (most likely due to a circular import) (/Users/haniyyah/miniconda3/envs/ezTrack/lib/python3.8/site-packages/panel/config.py)`
Would you have any insight into this?
Thank you!

**Comment by ZachPenn** [comment]
I think this has to do with with an incompatibility resulting from an update to jinja2 (which is a dependency of one of the packages ezTrack uses).  I think by explicitly stating an earlier jinja2 version during install the error will be resolved.

Try:
```
conda create -y -n ezTrack -c conda-forge python=3.8 pandas=1.3.2 matplotlib=3.1.1 opencv=4.5.3 jupyter=1.0.0 holoviews=1.14.5 scipy=1.7.1 scikit-learn=0.24.2 bokeh=2.3.3 jinja2=3.0.3 tqdm
```
