### ISSUE TITLE
Issue - Defining Regions of Interest 

### ISSUE THREAD

**Issue by sofiaitorres** [denisecailab/ezTrack#38]
Hi there! Hope you're doing well.

When I try to define the regions of interest in my cropped frame (specifically I'd like to divide the frame in two rectangles), I get a "**No Regions to Draw**" message. I try to draw but I can't (there's not even a box with a plus sign). 

Just wanted to know how to fix this, if even possible! Let me know if you need more information. I have attached a picture of the issue.

Best,
Sofía
<img width="324" alt="Screen Shot 2021-10-14 at 6 01 38 PM" src="https://user-images.githubusercontent.com/77503430/137401933-481abd56-fa67-49bc-9670-ca9ba148eb0c.png">

**Comment by ZachPenn** [comment]
You need to have defined the names of your regions in Cell 2.  I'm assuming your region_names is still set to `None`.
As an example.

```

video_dict = {
    'dpath'        : "/Users/DeniseCaiLab/Videos",  
    'file'         : 'Video.mp4',
    'start'        : 0, 
    'end'          : None,
    'region_names' : ['Left','Right','Center'],
    'dsmpl'        : 1,
    'stretch'      : dict(width=1, height=1)
}

```
