### ISSUE TITLE
ImportError when importing LocationTracking_Functions

### ISSUE THREAD

**Issue by Wulin-Tan** [DeniseCaiLab/ezTrack#39]
**#Hi, ezTrack is a pretty cool and straightforward tool.**
**#we can successfully install it when we follow the README file. but when we tried to run the code in jupyter notebook, we came across the error below:** 

ImportError                               Traceback (most recent call last)
<ipython-input-1-cc1b517488a0> in <module>
      6 import matplotlib.pyplot as plt
      7 import pandas as pd
----> 8 import LocationTracking_Functions as lt
      9 import holoviews as hv

~\Downloads\ezTrack-1.1\LocationTracking_Functions.py in <module>
     42 from holoviews import streams
     43 from holoviews.streams import Stream, param
---> 44 hv.notebook_extension('bokeh')
     45 warnings.filterwarnings("ignore")
     46 

~\anaconda3\envs\ezTrack\lib\site-packages\param\parameterized.py in __new__(class_, *args, **params)
   3098         inst = class_.instance()
   3099         inst.param._set_name(class_.__name__)
-> 3100         return inst.__call__(*args,**params)
   3101 
   3102     def __call__(self,*args,**kw):

~\anaconda3\envs\ezTrack\lib\site-packages\holoviews\ipython\__init__.py in __call__(self, *args, **params)
    112 
    113     def __call__(self, *args, **params):
--> 114         super(notebook_extension, self).__call__(*args, **params)
    115         # Abort if IPython not found
    116         try:

~\anaconda3\envs\ezTrack\lib\site-packages\holoviews\util\__init__.py in __call__(self, *args, **params)
    703 
    704         if selected_backend is None:
--> 705             raise ImportError('None of the backends could be imported')
    706         Store.set_current_backend(selected_backend)
    707 

ImportError: None of the backends could be imported

**And the LocationTracking_Functions.py is in the same folder as LocationTracking_Individual.ipynb**
**#any suggestion? Thank you.**

**Comment by ZachPenn** [comment]
Did you follow the install instructions exactly?  Is the correct conda environment activated?  From the error report it looks like this is an issue with loading package dependencies, rather than anything with ezTrack itself.
