### ISSUE TITLE
Could you help me out from this problem showing "File not found"

### ISSUE THREAD

**Issue by engramer** [denisecailab/ezTrack#43]
Hi, 

I am a very beginner for Python. 
I have tried to analyze my mouse contextual test video files. 
In my hand, I can select region of interest. 
Like this, 
![Screen Shot 2021-12-02 at 4 55 51 PM](https://user-images.githubusercontent.com/93405921/144906152-34eb4557-f6ec-43b5-ae54-4176101946fe.png)
. 

However, when I went to the next step, I got an error like this. 
![Screen Shot 2021-12-02 at 4 56 04 PM](https://user-images.githubusercontent.com/93405921/144906292-644422c5-f1b5-4f91-9759-18c295b60f5d.png)

I don't know how to fix this issue. I set the path of my files and directories. 
![Screen Shot 2021-12-02 at 4 55 36 PM](https://user-images.githubusercontent.com/93405921/144906398-4dd83b5c-98ae-4665-ba85-de112efc34c0.png)

Could you help me out for this problem? 
Thank you for your time and attention.

**Comment by ZachPenn** [comment]
Hi there.  I'm really not sure, but I see that you're using a relatively older version of ezTrack.  I would recommend downloading the most up to date files and reinstall the conda environment with the most up to date instructions.  To uninstall the current environment, you can use the following command in terminal: `conda remove --name ezTrack --all`.

Let me know if this doesn't solve your issue.

**Comment by engramer** [comment]
Hi, I really appreciate it. When I remove all old ezTrack files and reinstall them, the code works well. I can be back on my experiments. Thanks a lot!!

**Comment by ZachPenn** [comment]
No problem.  Hope experiments go well!
