### ISSUE TITLE
LocationTracking_BatchProcess bug

### ISSUE THREAD

**Issue by LiRenping199603** [denisecailab/ezTrack#44]
I used the LocationTracking_BatchProcess scrip to handle my videos.It  worked well with no Defined ROI but got an error for processing more than 8 videos with Defined ROI.Here are part of the error:
KeyError                                  Traceback (most recent call last)
~\anaconda3\envs\ezTrack\lib\site-packages\pandas\core\indexes\base.py in get_value(self, series, key)
   3102             return self._engine.get_value(s, k,
-> 3103                                           tz=getattr(series.dtype, 'tz', None))
   3104         except KeyError as e1:
IndexError: index out of bounds
Hope it will be fixed,thanks!

**Comment by ZachPenn** [comment]
Could you please provide me with two things:
1. The printed output that ezTrack presents before the error emerges
2. The full text from the error report (at least I think there is more, but I could be wrong)

**Comment by LiRenping199603** [comment]
Error with ROI：


Well without ROI：




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "denisecailab/ezTrack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月10日(星期五) 凌晨2:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [denisecailab/ezTrack] LocationTracking_BatchProcess bug (Issue #44)





 
Could you please provide me with two things:
  
The printed output that ezTrack presents before the error emerges
 
The full text from the error report (at least I think there is more, but I could be wrong)
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ZachPenn** [comment]
Can you pease provide the full error reports and the info I requested before?

**Comment by LiRenping199603** [comment]
Sorry，i'm a beginner of Python，unable to make a full error report.Maybe you want the jupyter error page，I put it in email attachment.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "denisecailab/ezTrack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月10日(星期五) 上午10:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [denisecailab/ezTrack] LocationTracking_BatchProcess bug (Issue #44)





 
Can you pease provide the full error reports and the info I requested before?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ZachPenn** [comment]
Just what is printed out in Jupyter is fine.  Unfortunately, I am unable to see anything.  Perhaps your attachment didn't work when responding via email.

**Comment by LiRenping199603** [comment]
It was wrong format，trythis




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "denisecailab/ezTrack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月10日(星期五) 上午10:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [denisecailab/ezTrack] LocationTracking_BatchProcess bug (Issue #44)





 
Just what is printed out in Jupyter is fine.  Unfortunately, I am unable to see anything.  Perhaps your attachment didn't work when responding via email.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ZachPenn** [comment]
Still nothing.  You might have better luck uploading directly on github.

**Comment by LiRenping199603** [comment]
[LocationTracking_BatchProcess - Jupyter Notebook.pdf](https://github.com/denisecailab/ezTrack/files/7689889/LocationTracking_BatchProcess.-.Jupyter.Notebook.pdf)
![image](https://user-images.githubusercontent.com/95870470/145511720-6220444f-fba3-4346-97ec-0e7c2398ae49.png)
![image](https://user-images.githubusercontent.com/95870470/145511750-eef97226-1d06-4c82-a56c-7636e4e584bd.png)

**Comment by ZachPenn** [comment]
Have you tried opening `saline-1.avi`?  This is the file that is being processed when you run into an error, and as you can see in the output, the video is said to have 0 frames:

![image](https://user-images.githubusercontent.com/38541976/145577762-8009b2ea-e1b8-405a-8c46-23147f9f97ad.png)

If true, this will understandably result in an error and is not a bug in ezTrack.  In addition to opening the video manually, compare the file size for this video to the file size of other videos being processed.  My guess is that something was corrupted during acquisition.

**Comment by LiRenping199603** [comment]
saline-1.avi has been opened correctly in player 
![error1](https://user-images.githubusercontent.com/95870470/145593620-e572d618-4fc0-4d28-bc46-d73f641fe00d.png)
，
and I have tested another set of videos that gets same errors with processing up to 9th video.So hope you could take some time to solve this problem，ezTrack is useful for my work，thank a lot！
[LocationTracking_BatchProcess - error2.pdf](https://github.com/denisecailab/ezTrack/files/7693536/LocationTracking_BatchProcess.-.error2.pdf)

**Comment by LiRenping199603** [comment]
This error just emerge at  processing more than 8 videos with defineing ROI，here a success with no defineing ROI operation
![LocationTracking_BatchProcess - NoROI_0](https://user-images.githubusercontent.com/95870470/145595727-a2d01954-29f0-4aff-9185-207800d8fe2f.jpg)
，hope it‘s helpful for compare with the error

**Comment by ZachPenn** [comment]
Unfortunately, for reasons I won't delve into, the fact that it can process all the videos without the ROI has no real baring on the issue.  If you were to open the frame by frame output csv for the saline-1.avi when you process it without ROIs video I am almost certain it will be an empty file.  Also, it is incredibly unlikely that it has anything to do with it being the 8th video.  People from many labs routinely process many more than 8 videos with ezTrack.  

The thing that needs to be figured out is why the frame is read as having 0 frames by ezTrack.  I think you will find in both of your error situations that if you were to process the 8th file (e.g. saline-1.avi) in the individual tracking (LocationTracking_Individual.ipynb) that you will run into the exact same error.

**Comment by ZachPenn** [comment]
Look at the output from all of your saline videos and you'll see there is no animal, even when it runs:
![image](https://user-images.githubusercontent.com/38541976/145601221-3cd42da0-83ea-49d5-a2dd-291c45f8fbae.png)

**Comment by LiRenping199603** [comment]
Thank you so much for your help.This error turely came from out my videos that has been croped by OpenCV.Sorry to have wasted your time，thanks again.

**Comment by ZachPenn** [comment]
No worries. Glad you got it sorted out.
