### ISSUE TITLE
When I changes the folder that I saved freezing videos, the script shows "not found".

### ISSUE THREAD

**Issue by engramer** [DeniseCaiLab/ezTrack#46]
Hi, 

For a while, after I reinstalled the new version of ezTrack, I didn't have any problem with finding freezing video files. 
However, when I changed the folder (path) to analyze other video files, the script didn't read them. 

![Screen Shot 2021-12-22 at 12 20 14 PM](https://user-images.githubusercontent.com/93405921/147131052-c57d4721-9075-483a-a78e-77f0c83bc4ec.png)

In the screenshot, 
"/Users/sungmo/Dropbox/tracking_in_python/original_test_video_CT2/ADFP2/m1_behaviour.avi" is a new path. 
The original one was "/Users/sungmo/Dropbox/tracking_in_python/original_test_video_CT1/ADFP2/m1_behaviour.avi".

I only changed the folder to another. 

Could you help me out? 
Thank you for your time and attention.

Best,

**Comment by ZachPenn** [comment]
It looks like you might be using Dropbox, which may have file permission issues.  If you move the files locally to your computer do you have the same issues?

**Comment by engramer** [comment]
It works!!! 
I didn't know that Dropbox permission causes the problem. 

Thank you so much for your quick responses. 
Have a great rest of the day!

**Comment by ZachPenn** [comment]
Great!  I haven't used Dropbox much but I remember encountering this issue a few years back with someone else.  There's probably a workaround.  It may be permission issue, or it may be how Dropbox files need to be referenced based upon how they are mounted to your drive.
