### ISSUE TITLE
error when calling Track Location and Save Results to .csv File on notebook

### ISSUE THREAD

**Issue by litaldavar** [DeniseCaiLab/ezTrack#49]
Hello I tried to run your notebook LocationTracking_Individual

everything run fine until I got to 8c. Track Location and Save Results to .csv File

![image](https://user-images.githubusercontent.com/4908360/154501616-17204c73-40ce-4162-a991-abd852ee722b.png)

Please help

**Comment by wmau** [comment]
In the cell where you define `video_dict` try setting `'region_names': None` then running the pipeline from the beginning.

**Comment by litaldavar** [comment]
Thanks that did it
