### ISSUE TITLE
Location Tracking Batch Processing Failing to Transition to other videos in folder

### ISSUE THREAD

**Issue by gibbont2** [DeniseCaiLab/ezTrack#52]
Cell 2 output shows all videos in the folder are recognized. Videos are all same length, camera position, resoltuion/FPS. First video in folder is successfully analyzed and produces seemingly correct tabulated results but then I receive the following error instead of continuing to analyze the next video. 
![image](https://user-images.githubusercontent.com/103907529/163737271-f11c52f2-209f-4b21-bc69-43da05f44c26.png)

![image](https://user-images.githubusercontent.com/103907529/163737282-1d63e6aa-52ce-4297-bd73-3cf1f516607d.png)

Thanks.

**Comment by ZachPenn** [comment]
I could use a bit more context.  Have you processed the first file that is throwing an error individually without issue? Are you drawing regions of interest? Could you please provide a pdf of your full batch processing notebook so I can see your parameters and try to replicate on my end?

**Comment by gibbont2** [comment]
> I could use a bit more context. Have you processed the first file that is throwing an error individually without issue? Are you drawing regions of interest? Could you please provide a pdf of your full batch processing notebook so I can see your parameters and try to replicate on my end?

That was on an institution computer that I am not at right now. I will send that over by tomorrow. The first file processes without issue and outputs the correct results. ROI's are drawn. 

Also on my own computer I am receiving an error that I have encountered previously with no solution besides using an alternative version of the program. It is a syntax error regarding 'dsmpl' as follows 
![image](https://user-images.githubusercontent.com/103907529/164946000-3fba04ac-7268-4240-bcd2-518cdb13aced.png)

I appreciate the help.

**Comment by gibbont2** [comment]
Same issue occurs regardless of down sampling value. Videos are .mp4

**Comment by ZachPenn** [comment]
This error is because you don’t have a comma after your list containing your regions of interest on the line above where you set dsmpl:
`'dsmpl' : [‘region1’,  ‘region2’],`
