### ISSUE TITLE
The third step encountered some problems

### ISSUE THREAD

**Issue by su-type** [DeniseCaiLab/ezTrack#53]
Thank you very much for the quick tool you have developed, which brings great convenience to those who need basic scientific research, especially for people like me who have basically no programming experience. But I encountered a small problem in the process of using, I don't know how to deal with it, it makes me a little confused, so I ask you for help, I hope to get your answer
![image](https://user-images.githubusercontent.com/103994729/163976975-0011bb2e-af61-4447-ae01-c5a0c63ae147.png)

**Comment by ZachPenn** [comment]
The problem is that you changed `cropmethod='Box'` to 'cropmethod='LP.mp4'` and this is not a valid entry.  You shouldn't need to change crop method.

**Comment by su-type** [comment]
Thank you very much for your timely reply. Under your guidance, I solved
this problem. When I used your tools to get the images I wanted, I thought
your work was great.
However, I encountered two small problems: the first problem is that when
the program was running step 8 C, I encountered some problems, and there
was a report like this:"
WARNING:wire_krntoolarge.Revertingtormv_wire=Falseforframe8". For detailed
screenshots, see Attachment 1.
I look forward to hearing from you very much. I see you as a sharing
scientist and I want to learn from you and share with my friends the
knowledge and skills I have acquired with you

Zach Pennington ***@***.***> 于2022年4月20日周三 09:52写道：

**Comment by ZachPenn** [comment]
As it states in the warning, this means that your `wire_krn` under tracking parameters is too large, resulting in removal of the animal.  When this happens, on individual frames the wire removal algorithm isn't emplemented.

I encourage you to read our methods paper that explains the use of ezTrack and has lots of helpful tips and tricks.  It is open access:
https://currentprotocols.onlinelibrary.wiley.com/doi/10.1002/cpz1.255

**Comment by su-type** [comment]
Thank you very much for your prompt reply. The link you gave on how to use
eztrack is great and the instructions inside are very detailed. I'm sure
this will solve a lot of problems for me. Thank you again for your
contribution to the scientific work, your work has greatly helped
neuroscience researchers with no programming experience. Thanks again and
have a nice life

Zach Pennington ***@***.***> 于2022年4月20日周三 20:40写道：
