### ISSUE TITLE
Failure in LocationTracking_BatchProcess

### ISSUE THREAD

**Issue by evellynmayla** [DeniseCaiLab/ezTrack#55]
I'm trying to use the Location tracking Batch process in my Open Field videos, but received a "Type error". 
All the files are in the same folder and have the same properties (FPS, camera position, etc). 
The code run without problem until step 7, when it process the first video, but fail to analyze the next and gives me the following error message. 

I will send prints of all my cells, just in case. 

I'm a beginner in this Python world, so Thanks so much for any help.
![cell 1](https://user-images.githubusercontent.com/105449106/168129552-d72e5f0b-7998-4c67-a9d4-2946f8e0a4ee.jpg)
![cell 2 and files](https://user-images.githubusercontent.com/105449106/168129554-29ef0ff0-4a85-494c-837c-28617a7ab03b.jpg)
![files](https://user-images.githubusercontent.com/105449106/168129555-e1cca385-728d-4f27-b4d2-9f1665738962.jpg)
![cell 3](https://user-images.githubusercontent.com/105449106/168129557-e1afbeec-f08f-4df5-8ef6-2b7b3242408b.jpg)
![cell 4](https://user-images.githubusercontent.com/105449106/168129560-5d920905-5776-45d5-9a5d-5a83c8cd624d.jpg)
![cell 5](https://user-images.githubusercontent.com/105449106/168129562-c1c34605-35fe-4e8c-bd96-c056d55a8a2b.jpg)
![cell 6a](https://user-images.githubusercontent.com/105449106/168129564-02e7949b-fb9b-4a99-a641-6f6b02929cbc.jpg)
![cell 6b e 7](https://user-images.githubusercontent.com/105449106/168129565-cc8342ef-0c26-429f-9a2a-91305afdee4b.jpg)
![cell 7](https://user-images.githubusercontent.com/105449106/168129568-95c45a7c-05cb-41b3-94ca-7f05c3b0be69.jpg)
![cell 7 error](https://user-images.githubusercontent.com/105449106/168129569-0c4509b8-0619-4bd2-a9ef-32ea3dffe0e3.jpg)

**Comment by ZachPenn** [comment]
Hi! Very simple but understandable mistake.

Where you put `bin_dict = {None}`, it should instead be `bin_dict = None`

**Comment by evellynmayla** [comment]
Hello!

It was exactly this. Now  is all working perfectly. 

Thanks a lot !!
