### ISSUE TITLE
Step 3, Output image is not displaying

### ISSUE THREAD

**Issue by saabreenuh** [DeniseCaiLab/ezTrack#56]
Hello! 
I have a question regarding step 3's output. I run step 3 and I got a text output corresponding to the video I wanted to process, but there was no image output that I could then crop. Additionally, when I try to run step 4, the same issue occurs, there is no image output. Any advice how to correct this? 

Thank you in advance!
<img width="920" alt="Screen Shot 2022-05-16 at 11 58 18 AM" src="https://user-images.githubusercontent.com/45496437/168665886-190eace1-4f90-43b3-af05-26249ee32630.png">

**Comment by ZachPenn** [comment]
You should try to increase output size at the top of the code cell.  50 for you is likely too small.  The same applies for other cells.

You might like our protocols paper: https://currentprotocols.onlinelibrary.wiley.com/doi/full/10.1002/cpz1.255.  It covers this and many other useful features.

**Comment by matinsaba** [comment]
Hi, 

I have increased the output_size and yet I still can't see the output.
