### ISSUE TITLE
Key Error

### ISSUE THREAD

**Issue by saabreenuh** [DeniseCaiLab/ezTrack#57]
Hello again! 

Thanks for being so punctual with your replies! 

I had another question.  When trying to define ROI and when trying to define scale, I am met with an error:
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-13-3a42a627c53b> in <module>
----> 1 img_scl, video_dict['scale'] = lt.DistanceTool(video_dict)
      2 img_scl

~/Various Documents/Vole Research Stuff/ezTrack-master/LocationTracking/LocationTracking_Functions.py in DistanceTool(video_dict)
   2212     #Make reference image the base image on which to draw
   2213     image = hv.Image((
-> 2214         np.arange(video_dict['reference'].shape[1]),
   2215         np.arange(video_dict['reference'].shape[0]),
   2216         video_dict['reference']))

KeyError: 'reference'

How might I resolve this?

Thank you again in advance! 

<img width="1126" alt="Screen Shot 2022-05-16 at 7 00 23 PM" src="https://user-images.githubusercontent.com/45496437/168713067-2eb70fb9-4f43-42fa-8e3b-4dd745b00c53.png">
<img width="1149" alt="Screen Shot 2022-05-16 at 7 00 33 PM" src="https://user-images.githubusercontent.com/45496437/168713075-1a027abf-d02a-4173-8ba4-5274391d8fed.png">

**Comment by ZachPenn** [comment]
This likely indicates that a reference hasn't been created. Please note that this has to be done every in each time you run a video and when you refresh the kernel.
