### ISSUE TITLE
Cropping and ROI

### ISSUE THREAD

**Issue by shannon-g11** [DeniseCaiLab/ezTrack#59]
Thank you for creating this software, it is really helpful. I am currently using it to track the distance travelled of mice in an open field. When I use the program to measure the total distance, it works great on a video that only contains the box. 

However, I have tried using this to crop a video where there is movement outside the box (step #3) and I ran into issues. Everything appears to be working correctly, however, after selecting the region to crop, it's not reflected in the next steps. And if I don't crop the video, I get interference with where the centre of mass is for the animal. 
![Load and crop](https://user-images.githubusercontent.com/108802946/177539450-34bb45b7-1306-497e-ac40-7e6d6014ffba.png)

I'm also getting the same problem when I try to select an ROI - I am able to select the region but this isn't remembered. 
![ROI](https://user-images.githubusercontent.com/108802946/177539781-c1f64b18-1bf8-4811-b890-a4a4d12471b8.png)

I am guessing there is a step that I am missing, but I can't work out what this is. I have been through the detailed protocol and still can't find where I am going wrong. 

I hope that I can get some help on this issue. Thank you in advance.

**Comment by ZachPenn** [comment]
Have you tried running with Jupyter Notebook?  I too am a vscode user but Holoviews' interactive plotting tools have not been terribly reliable outside of Jupyter Notebook/Juptyer Lab.   It wouldn't surprise me if this is the issue.

**Comment by shannon-g11** [comment]
This appears to be the issue - I never even thought to try running with Jupyter Notebook. 
Thank you for the help and the quick reply. :)
