### ISSUE TITLE
First cell fails to run/load packages

### ISSUE THREAD

**Issue by gibbont2** [DeniseCaiLab/ezTrack#60]
I had to reinstall all programs on my computer including everything python related and I am not having issues running the first cell on locationtracking_batch process. 

This is the error message.
![image](https://user-images.githubusercontent.com/103907529/181638217-d660842c-554a-4514-b826-603d40ea84e2.png)

Things I have tried:

- I have removed the ezTrack environment multiple times  (conda env remove -n ezTrack), recreating the environment using "conda create -y -n ezTrack -c conda-forge python=3.8 pandas=1.3.2 matplotlib=3.1.1 opencv=4.5.3 jupyter=1.0.0 holoviews=1.14.5 scipy=1.7.1 scikit-learn=0.24.2 bokeh=2.3.3 jinja2=3.0.3 tqdm" (exact cmd copied from my anaconda terminal.). I still get the same error. 
- Creating environment with scipy=1.7.3
- Rolling back numpy to 1.22.3, 1.21.5. (creates issues with holoviews)
- Varying combinations of different pandas, scipy, numpy, and holoviews versions
- About 10 different program rollbacks as more things became incompatible with each other but I did not find a working combination

This issue began a month ago and is still continuing. I'm using win64 & chrome.

Here is conda list using exact environment create from installation instructions:

![image](https://user-images.githubusercontent.com/103907529/181642478-5d2fb500-fbeb-44d6-b0c0-106dad414716.png)
![image](https://user-images.githubusercontent.com/103907529/181642567-a9ebfca0-16e3-4e02-83d4-6fd46ca14118.png)
![image](https://user-images.githubusercontent.com/103907529/181642624-b0e8ce79-a024-42cc-93e3-90568a3f1337.png)

Thanks!

**Comment by ZachPenn** [comment]
Apologies for the delay.  Have you tried adding the numpy version to the conda install command as follows?
```
conda create -y -n ezTrack -c conda-forge python=3.8 pandas=1.3.2 matplotlib=3.1.1 numpy=1.22.3 opencv=4.5.3 jupyter=1.0.0 holoviews=1.14.5 scipy=1.7.1 scikit-learn=0.24.2 bokeh=2.3.3 jinja2=3.0.3 tqdm
```

I know you said you tried to rolling back numpy to this version, but how conda does a rollback vs. creating a fresh environment is different from what I understand.  At least on my mac this environment works.  Will try on a windows later today.  

You'll of course want to uninstall ezTrack environment before doing this.  The following command will remove the environment:
```
conda remove --name ezTrack --all
```

**Comment by gibbont2** [comment]
> 

That did the trick.

Much appreciated and as always thank you for providing this program and continued support for it.
