### ISSUE TITLE
Individual location tracking 8b - animal removed from example frames

### ISSUE THREAD

**Issue by armorningstar** [DeniseCaiLab/ezTrack#67]
I've never had this issue in the past, but yesterday I started having an issue where the mouse was removed from the frame in the location tracking examples (see photo below). Sometimes the mouse is removed in 1 or 2 of the frames, and in the other example frames the tracker is spot on, other times all 4 examples are bad - genuinely no clue why.

I've tried adjusting all of the tracking_params, but nothing seems to do the trick. I'm confident that the start and end frames in step 2 are set to the correct duration, so I don't see how it could be frames from before the animal appears in the video. 

If I go ahead and run the tracking, the video in step 10 is super off, it's like it's just randomly moving around.
Any idea what might be going on? @ZachPenn 

<img width="432" alt="Screenshot 2022-12-01 at 12 31 47 PM" src="https://user-images.githubusercontent.com/119632618/205167190-2af23cca-3632-403b-9aa3-5657a0fb6d34.png">

**Comment by ZachPenn** [comment]
The images on the left are raw video.  If the animal is not there, it likely was not in the box.  Have you watched the video in its entirety?

**Comment by armorningstar** [comment]
Yes, we get the frame rate (~30 fps) from a MatLab script and then multiply that by the start time (time animal entered the box) in seconds to get the start frame. For a 5 minute trial (300 sec) where the frame rate = 30 fps and the animal was put in at t = 30 seconds, start frame = 900 and end frame = 9900. Our videos are always ~ 6 minutes long, so we have more than 5 minutes of the animal in the box. 

When I watch the video in step 10, the mouse is in the box for the entire duration, but the tracker is completely off. Is there a way that the reference frame (from step 5) is somehow being used in step8, because in the raw video the mouse is there for the duration I've specified.

**Comment by armorningstar** [comment]
I tried another batch of videos and it seems like this issue is only happening with .mov files (or .mov files that were converted to .mp4) but not on original .mp4 files. I know ezTrack is supposed to be compatible with .mov files - is there anything in the code that needs to be changed when using different file types?

**Comment by ZachPenn** [comment]
Sorry for the delay.  My guess is that the issue lies in how the videos are being converted to mov, rather than mov files per se.  Often times when converting videos they are compressed, and ezTrack is not compatible with all forms of compression - specifically, temporal compression.  When videos are initially loaded in ezTrack, the total number of frames is printed.  Does that list the expected 9900 frames for the mov files?
