### ISSUE TITLE
LocationTracking_BatchProcess Issue with dif as a variable

### ISSUE THREAD

**Issue by DestinyDoll922** [DeniseCaiLab/ezTrack#69]
I'm new to python, learning it for my lab but I am unable to identify the error in the code to cause this? I haven't edited the functions page. 

[](url)
![Error](https://user-images.githubusercontent.com/125494637/219111468-973901e3-ceaa-4d9e-9c27-c90ff62af6bc.PNG)

**Comment by ZachPenn** [comment]
You most likely specified the parameters in the preceding section incorrectly.  In particular, please be sure that for your tracking params you set `method` to 'light', 'dark', or 'abs', with not caps.

**Comment by DestinyDoll922** [comment]
Yes thank you!
