### ISSUE TITLE
Failure to display a video in FreezeAnalysis_Individual

### ISSUE THREAD

**Issue by 726akaw** [DeniseCaiLab/ezTrack#70]
Hello,

When  I tried to display a section of the video with motion and freezing, I got an error:
 File "/var/folders/fp/x8cfxc_j4wd3dd75zrvfvh8h0000gn/T/ipykernel_81410/663519892.py", line 6
    'save_video' : False
    ^
SyntaxError: invalid syntax

Could you help me out with this problem?

Thanks.

<img width="1134" alt="スクリーンショット 2023-02-20 15 33 43" src="https://user-images.githubusercontent.com/125878084/220094286-ec0cc46e-296f-4989-903d-6ccbec8534e2.png">

**Comment by florianduclot** [comment]
@726akaw , I'll give that one a shot:
I think you have a missing comma at the end of the `'resize'` line.

**Comment by 726akaw** [comment]
@florianduclot 
oh, it's a simple mistake. I appreciate your advice. Thank you so much!
