### ISSUE TITLE
Problem in Define Regions of Interest

### ISSUE THREAD

**Issue by aridelus** [DeniseCaiLab/ezTrack#72]
When I draw a new region in the Anaconda prompt the following line appears and I can only restart the kernel 

 File "C:\Users\giana\anaconda3\envs\ezTrack\lib\site-packages\tornado\iostream.py", line 182, in advance
        assert 0 < size <= self._size
 AssertionError
[I 12:33:18.955 NotebookApp] Saving file at /Downloads/ezTrack-master/LocationTracking_Individual.ipynb
[W 12:33:18.956 NotebookApp] Notebook Downloads/ezTrack-master/LocationTracking_Individual.ipynb is not trusted

**Comment by ZachPenn** [comment]
This is likely the result of recent package incompatibility issues that emerged.  Please see the latest install instructions in the ezTrack wiki.
