### ISSUE TITLE
Problem labelling ROI and pixel distance

### ISSUE THREAD

**Issue by vlucky312** [DeniseCaiLab/ezTrack#74]
Hi, I'm currently having issues with labelling the ROI and distance in pixels (cells 6, 7a) in location tracking. I am able to run both cells, but the labels do not display.  Any help on this issue would be much appreciated!

![Screen Shot 2023-06-12 at 10 44 36 AM](https://github.com/denisecailab/ezTrack/assets/136354624/6a782db1-d940-4ba8-b719-339dcd1bb3e4)
![Screen Shot 2023-06-12 at 10 44 56 AM](https://github.com/denisecailab/ezTrack/assets/136354624/f79fad64-f964-40c6-950f-2baff7a7b506)

**Comment by ZachPenn** [comment]
Hi.  Thanks for bringing this to my attention.  This appears to be an issue with one of ezTrack's package dependencies and will require a modified installation.  I have it working again on my computer and should have fresh install instructions in the next couple days.  Please reach out if you fail to hear from me in a week.

**Comment by ZachPenn** [comment]
Could you please install the following environment from the terminal, after removing your current ezTrack environment (`conda remove --name ezTrack --all`):

`
conda create -y -n ezTrack -c conda-forge python=3.8 pandas=1.3.2 matplotlib=3.1.1 numpy=1.22.3 opencv=4.5.3 jupyter=1.0.0 holoviews=1.14.5 scipy=1.7.1 scikit-learn=0.24.2 bokeh=2.3.3 jinja2=3.0.3 pyviz_comms=2.1.0 tqdm
`

Please let me know if this fixes your problem.

**Comment by vlucky312** [comment]
Hi, it fixed the problem, thank you for all your help!

**Comment by ZachPenn** [comment]
Glad to hear it!

**Comment by JSPinho13** [comment]
Hi
I am facing the same problem. 
I did the installation as you suggested but when my jupyter opened, in the corner appear python(ipykernel) and not python3 like before.

When i label the ROIs just the first ROI appear labeled. All the other Rois appear without the label in the top. 
The select two points of known distance, the cell runs but did not open the window to draw the points.

Can you help me?

Best
Julia

**Comment by ZachPenn** [comment]
I would try the latest install instructions that I just posted on the ezTrack wiki.  Several similar and recent issues emerged that have been resolved by this (most notably for users of newer macs).

**Comment by JSPinho13** [comment]
Hi

Thanks

I installed : conda create -y -n ezTrack -c conda-forge python=3.9.16 jupyter=1.0.0 numpy=1.24 scipy=1.11.1 pandas=2.0.3 opencv=4.7.0 holoviews=1.15.0 bokeh=2.4.0 pyviz_comms=2.1 jinja2=3.1.2 scikit-learn=1.3.0 matplotlib=3.7.2 tqdm=4.65.0

Now problem fixed!

Many thanks 
Best
Julia
