### ISSUE TITLE
Unable to get matplotlib 3.1.1

### ISSUE THREAD

**Issue by vtbrak** [DeniseCaiLab/ezTrack#75]
When I try to install EZtrack on a new computer I get the following error and can't continue the installation. I'm installing a Apple Silicon Macbook.

PackagesNotFoundError: The following packages are not available from current channels:

  - matplotlib=3.1.1

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

**Comment by ZachPenn** [comment]
Hi.  Thanks for posting this here.  I am aware of this issue and will have my hands on a silicon macbook next week and will be sorting out a fix.  Please stay tuned.

**Comment by vtbrak** [comment]
Thanks Zach! This tool is so great for my undergraduates to use and I really appreciate your continued work on it.

**Comment by ZachPenn** [comment]
Hi,

I tried the following on one mac with silicon chip and it resolved issues.  However, on my personal M2 max I'm having issues.  I'm still trying to track down whether it's an issue with the newer chip, browser, or osx version.  If you could test this and let me know how things go for you I'd greatly appreciate it.  Additionally, if you could let me know what osx version you're currently using and what browser that would be helpful.

`
conda create -y -n ezTrack -c conda-forge python=3.9.16 pandas=1.3.2 matplotlib=3.7.2 numpy=1.22.3 opencv=4.5.3 jupyter=1.0.0 holoviews=1.14.5 scipy=1.7.1 scikit-learn=0.24.2 bokeh=2.3.3 jinja2=3.0.3 pyviz_comms=2.1.0 tqdm
`

Make sure you remove the existing environment first

`
conda remove --name ezTrack --all
`

**Comment by vtbrak** [comment]
Thanks Zach,

I'll try this out today. I'm on a regular M2 with 16GB of ram. Running
ventura 13.3. II typically use arc (chromium based) for the jupyter
notebooks but my student have been using safari.

Eric

**Comment by vtbrak** [comment]
Hi Zach,

That gets everything downloaded! I can get it to work in chrome but it
won't display a video for step 3 "load video and crop.." and nothing else
works after that when i tried in arc and in safari. Even in chrome I
have trouble when it is trying to display something like the crop or the
defining the arena or the scale points.

Thanks Eric

**Comment by ZachPenn** [comment]
Bummer.  Thanks for letting me know.  It seems the issue results from some sort of incompatibility between ezTrack package dependencies (Holoviews and Bokeh, specifically) and either some of the silicon macs or ventura.  Unfortunately, I've tried updating several combos of dependencies to no avail.  Sadly, this is going to be a long fix that could require me redoing all of the visualizations with a different plotting package.  

In the meantime, if you have any macs not running Ventura they will likely work.  Additionally, any windows computer will also likely work.

Sorry for the inconvenience.  It really is a pain.  As I said, I have similar issues on my new computer.

**Comment by vtbrak** [comment]
I can only imagine how much of a pain that is. Thank you for your continued effort on the project. I love it and pass it it along to anyone who is doing arena behavior.

I was really excited to see how fast the Apple silicon Macs would process the files. Oh well. Just means my students have to come into the lab to analyze.

Eric

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by vtbrak** [comment]
Just so you have some more information. I just had a student try to get it
up and running on an M1 with Catalina installed. The new create command
details worked for her but she ran into the same visualization problem.

**Comment by ZachPenn** [comment]
Good news is that I seem to have a conda environment that is working on my M2 Max running Ventura 13.4.1 with Google Chrome.  I was able to get through the entire location tracking module using all visualization and selection tools (roi, cropping, masking, etc).  Fingers crossed it will work for you all.

Please give this a try and let me know if it works.  I will also be testing on a few different computers with various operating systems we have around the lab.

After first removing your old environment:
`conda remove --name ezTrack --all`

Try creating this environment:
`conda create -y -n ezTrack -c conda-forge python=3.9.16 jupyter=1.0.0 numpy=1.24 scipy=1.11.1 pandas=2.0.3 opencv=4.7.0 holoviews=1.15.0 bokeh=2.4.0 pyviz_comms=2.1 jinja2=3.1.2 scikit-learn=1.3.0 matplotlib=3.7.2 tqdm=4.65.0`

**Comment by vtbrak** [comment]
Awesome. I will give it a try and have my students do it as well

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by vtbrak** [comment]
It worked on my laptop! (Apple Silicon M2 16 gig ram Ventura 13.3) I'll
report back if it works on some of the other and what their specs are.

**Comment by ZachPenn** [comment]
Thanks so much for your patience and help with this, Eric!  I also tried it on my older macbook and a windows in lab and it worked.  I am going to update installation instructions and close this issue.

**Comment by vtbrak** [comment]
Happy to help. My student said it worked on her computer as well. 13 inch MacBook Air 2020 dual core intel core i3.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
