### ISSUE TITLE
Red Cross could not be marked on the mouse

### ISSUE THREAD

**Issue by burger11361** [DeniseCaiLab/ezTrack#78]
When I was analyzing the behavior of mice, the Red Cross could not be marked on the mouse, but the horizontal coordinate was the same as the position of the mouse. I do not know how to solve this problem.
![1689910186662](https://github.com/denisecailab/ezTrack/assets/90259712/d4a85a68-9704-4efa-8454-636fe43f1d03)

**Comment by ZachPenn** [comment]
This is very odd.  Did you install the conda environment exactly as is instructed in the eztrack wiki?  This reminds me of an issue I saw when fixing some issues and was testing other versions of eztrack package dependencies.  

Separately, do you mice have a baseline preference for the side with vertical stripes?  I've found mine often do.

**Comment by burger11361** [comment]
Thank you very much, I re-installed it as is instructed in wiki. Now the red cross can mark on mice. It reveals that I deleted the eztrack unexpectedly.
And I haven't analysis the data, so I can't say whether my mice have baseline preference for the side with vertical stripes, I will tell you when I finish. Thanks again!

**Comment by burger11361** [comment]
now another problem comes up. The red cross can't mark on mice when it comes to right side, it is odd. 
****

**Comment by burger11361** [comment]
now another problem comes up. The red cross can't mark on mice when it comes to right side, it is odd.
![image](https://github.com/denisecailab/ezTrack/assets/90259712/b4005bec-69c7-4827-8b62-ea2b8b28b159)

**Comment by burger11361** [comment]
is it due to sensitivity or my parameter?
![image](https://github.com/denisecailab/ezTrack/assets/90259712/a3e32fbd-feaf-4482-9181-13883d180c73)

**Comment by burger11361** [comment]
![image](https://github.com/denisecailab/ezTrack/assets/90259712/5b5401b5-4c62-423d-b2a9-dc9582799586)
