### ISSUE TITLE
KeyError in Section 8c

### ISSUE THREAD

**Issue by thebooknerd** [DeniseCaiLab/ezTrack#83]
When I try to run section 8c, I keep getting the error in the image below. Does anyone have any idea what is causing this error and how I could fix it?
<img width="1127" alt="Screenshot 2023-10-19 at 2 14 23 PM" src="https://github.com/denisecailab/ezTrack/assets/148490454/115e6082-e17b-4761-a074-f78fefcf3be4">

**Comment by ZachPenn** [comment]
Did you draw the regions of interest 'Center', 'OpenTop', etc?  If you didn't, you need to either draw them or set `region_names : None` in cell 2.

**Comment by thebooknerd** [comment]
The regions for all of the regions of interest were drawn.
