### ISSUE TITLE
Problems with section 8c

### ISSUE THREAD

**Issue by ZachPenn** [DeniseCaiLab/ezTrack#88]
### Discussed in https://github.com/denisecailab/ezTrack/discussions/82

<div type='discussions-op-text'>

<sup>Originally posted by **thebooknerd** October 19, 2023</sup>
When I try to run section 8c, I keep getting the error in the image below. Does anyone have any idea what is causing this error and how I could fix it?
<img width="1127" alt="Screenshot 2023-10-19 at 2 14 23 PM" src="https://github.com/denisecailab/ezTrack/assets/148490454/ef89108d-4d3b-4aa6-959f-e656999d9f93">
</div>

**Comment by NguyenHKLe** [comment]
I have the same issue. When I checked the video_dict['roi_stream'], there were no updated coordinates of the ROI that I selected in section 6. The same thing happened for video_dict['mask'] in section 4.

**Comment by ZachPenn** [comment]
What are you running ezTrack with (jupyter, vscode, spyder)?

**Comment by NguyenHKLe** [comment]
I use jupyter notebook extension in vscode.

**Comment by ZachPenn** [comment]
I would try using jupyter notebook independent of vscode. I love vscode but unfortunately it doesn't always play well with some of the interactive notebook packages.

**Comment by NguyenHKLe** [comment]
I have tried again using jupyter notebook stand-alone version. It works, so the problem is probably due to vscode as you said.
